# Generated by Django 5.0.3 on 2024-03-22 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=500)),
                ('Code', models.CharField(max_length=255)),
                ('Value', models.IntegerField()),
                ('Useddate', models.DateTimeField()),
                ('IsActive', models.BooleanField(default=True)),
                ('Remarks', models.TextField(max_length=500)),
                ('Amount_Taken', models.IntegerField()),
                ('Usedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('Store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.store')),
            ],
        ),
    ]
