# Generated by Django 5.0.3 on 2024-03-24 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0003_coupon_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='Amount_Taken',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='Remarks',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='Usedby',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='Useddate',
        ),
        migrations.CreateModel(
            name='Coupon_used',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=500)),
                ('Code', models.CharField(max_length=255)),
                ('Value', models.IntegerField()),
                ('Store', models.CharField(blank=True, max_length=255, null=True)),
                ('Useddate', models.DateTimeField(blank=True, null=True)),
                ('Remarks', models.TextField(blank=True, max_length=500, null=True)),
                ('Amount_Taken', models.IntegerField(blank=True, null=True)),
                ('Qty', models.IntegerField(blank=True, null=True)),
                ('Usedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
